// Generated by gencpp from file vision_msgs/ObjInfo.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_OBJINFO_H
#define VISION_MSGS_MESSAGE_OBJINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct ObjInfo_
{
  typedef ObjInfo_<ContainerAllocator> Type;

  ObjInfo_()
    : name()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  ObjInfo_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::vision_msgs::ObjInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::ObjInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjInfo_

typedef ::vision_msgs::ObjInfo_<std::allocator<void> > ObjInfo;

typedef boost::shared_ptr< ::vision_msgs::ObjInfo > ObjInfoPtr;
typedef boost::shared_ptr< ::vision_msgs::ObjInfo const> ObjInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::ObjInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::ObjInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'vision_msgs': ['/home/dell/catkin_ws/src/vision_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::ObjInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::ObjInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::ObjInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::ObjInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::ObjInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::ObjInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::ObjInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c91b5fd50205b321c340d9450ec1eae6";
  }

  static const char* value(const ::vision_msgs::ObjInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc91b5fd50205b321ULL;
  static const uint64_t static_value2 = 0xc340d9450ec1eae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::ObjInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/ObjInfo";
  }

  static const char* value(const ::vision_msgs::ObjInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::ObjInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::vision_msgs::ObjInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::ObjInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::ObjInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::ObjInfo_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_OBJINFO_H
